-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

require("config/monitors")
require("config/variables")
require("config/autostart")
require("config/env")
require("config/aesthetics")
require("config/misc")
require("config/input")
require("config/binds")
require("config/windows")

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/


---------------------
---- VARIABLES -----
---------------------


-- Set programs that you use
local terminal    = "kitty"
local fileManager = "kitty -e yazi"
local menu        = "hyprlauncher"
local wallpaper   = "waypaper"
local browser     = "firefox"
local bar         = "waybar"
local notes       = "obsidian"
local editor      = "zeditor"
local bluetooth   = "blueman-manager"
local clock       = "tty-clock"
local code        = "code" ----Unused----



local wallpapers = {
    [2] = "/home/luminara/Pictures/wallpaper1.jpg",
    [3] = "/home/luminara/Pictures/wallpaper2.jpg",
    [4] = "/home/luminara/Pictures/wallpaper3.jpg",
    [5] = "/home/luminara/Pictures/wallpaper4.jpg",
    [6] = "/home/luminara/Pictures/wallpaper10.png",
    [7] = "/home/luminara/Pictures/wallpaper11.png",
    [8] = "/home/luminara/Pictures/wallpaper12.png",
    [9] = "/home/luminara/Pictures/wallpaper13.png",
}


-------------------
---- AUTOSTART ----
-------------------


-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--



-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/




-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------


----------------
----  MISC  ----
----------------



---------------
---- INPUT ----
---------------



---------------------
---- KEYBINDINGS ----
---------------------


----   MAINMOD   ----
local mainMod = "SUPER" -- Sets "Windows" key as main modifier


----   WINDOWS   ----
----     AND     ----
----  WORKSPACE  ----

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)


----   DEFUALT   ----
----    BINDS    ----

hl.bind(mainMod .. " + M",
    hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only



---- CUSTOM BINDS ----

----     APPS     ----

hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("kitty -e zsh -c 'cava; exec zsh'"))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("kitty -e zsh -c 'neofetch; exec zsh'"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("kitty -e cmatrix -b -C white"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("kitty -e tty-clock -C 6 -S -c -t -D"))
hl.bind(mainMod .. " + SHIFT + A",
    hl.dsp.exec_cmd("kitty -e zsh -c 'neofetch --ascii ~/Documents/Au5_ascii.txt --ascii_colors 39; exec zsh'"))
hl.bind(mainMod .. " + SHIFT + L",
    hl.dsp.exec_cmd("kitty -e zsh -c 'neofetch --ascii ~/Documents/L-ascii.txt --ascii_colors 39; exec zsh'"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(wallpaper))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("/home/luminara/Downloads/zen/zen"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(bar))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(notes))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + U", hl.dsp.exec_cmd(bluetooth))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("sh -c '/home/luminara/.config/hypr/scripts/waybar-toggle.sh'"))
-- hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(code))


----   HYPRSHOT   ----

hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind(mainMod .. " + delete", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd("hyprshot -m region"))


-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))


----    WINDOW    ----
----   MOVEMENT   ----

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

for i = 1, 9 do
    hl.bind(mainMod .. " + ALT + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end


---- CLOSE SPECIAL ----
----     MAGIC     ----

hl.bind(mainMod .. " + SHIFT + 1", function()
    hl.dsp.focus({ workspace = 1 })
    hl.dsp.exec_cmd("~/.config/hypr/bin/close_special.sh")
end)


----     CHANGE    ----
----   WALLPAPER   ----

for i = 2, 9 do
    hl.bind(mainMod .. " + ALT + " .. i,
        hl.dsp.exec_cmd("waypaper --wallpaper '" .. wallpapers[i] .. "'"))
end

for i = 2, 9 do
    hl.bind(mainMod .. " + CTRL + SHIFT + ALT + " .. i,
        hl.dsp.exec_cmd("sh -c \"echo 'Key: " ..
            i ..
            " Path: " ..
            wallpapers[i] ..
            "' >> /tmp/wallpaper_debug.log; waypaper --wallpaper '" ..
            wallpapers[i] ..
            "' && wal -i '" ..
            wallpapers[i] ..
            "' >> /tmp/wallpaper_debug.log 2>&1; pkill -x waybar; while pgrep -x waybar > /dev/null; do sleep 0.1; done; setsid waybar &\""))
end

for i = 2, 9 do
    hl.bind(mainMod .. " + CTRL + ALT + " .. i,
        hl.dsp.exec_cmd("sh -c \"echo 'Key: " ..
            i ..
            " Path: " ..
            wallpapers[i] ..
            "' >> /tmp/wallpaper_debug.log; waypaper --wallpaper '" ..
            wallpapers[i] ..
            "' && wal -i '" ..
            wallpapers[i] ..
            "'\""))
end


----  INCREASE OR  ----
---- DECREASE BLUR ----

hl.bind(mainMod .. " + ALT + Up", hl.dsp.exec_cmd("/home/luminara/.config/hypr/scripts/blur-adjust.sh size up"))
hl.bind(mainMod .. " + ALT + Down", hl.dsp.exec_cmd("/home/luminara/.config/hypr/scripts/blur-adjust.sh size down"))
hl.bind(mainMod .. " + ALT + Right", hl.dsp.exec_cmd("/home/luminara/.config/hypr/scripts/blur-adjust.sh passes up"))
hl.bind(mainMod .. " + ALT + Left", hl.dsp.exec_cmd("/home/luminara/.config/hypr/scripts/blur-adjust.sh passes down"))


-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + how to gel
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })


-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful
